from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.units import inch


def generate_pdf(
    filename,
    score,
    breakdown,
    matched_skills,
    missing_skills,
    strengths,
    improvements,
    suggestions
):

    # Create PDF document
    doc = SimpleDocTemplate(filename)

    # Get default styles
    styles = getSampleStyleSheet()

    # Store PDF elements
    elements = []

    # Title
    elements.append(
        Paragraph("<b><font size=18>AI Resume Ranker Report</font></b>", styles["Title"])
    )

    elements.append(Spacer(1, 0.25 * inch))

    # ATS Score
    elements.append(
        Paragraph(f"<b>ATS Score:</b> {score:.2f}%", styles["Heading2"])
    )

    elements.append(Spacer(1, 0.2 * inch))

    # Score Breakdown
    elements.append(
        Paragraph("<b>Score Breakdown</b>", styles["Heading2"])
    )

    for key, value in breakdown.items():

        elements.append(

            Paragraph(
                f"{key.title()} : {value}",
                styles["BodyText"]
            )

        )

    elements.append(Spacer(1, 0.2 * inch))

    # Matched Skills
    elements.append(
        Paragraph("<b>Matched Skills</b>", styles["Heading2"])
    )

    if matched_skills:

        for skill in matched_skills:

            elements.append(
                Paragraph(f"• {skill}", styles["BodyText"])
            )

    else:

        elements.append(
            Paragraph("No matched skills found.", styles["BodyText"])
        )

    elements.append(Spacer(1, 0.2 * inch))

    # Missing Skills
    elements.append(
        Paragraph("<b>Missing Skills</b>", styles["Heading2"])
    )

    if missing_skills:

        for skill in missing_skills:

            elements.append(
                Paragraph(f"• {skill}", styles["BodyText"])
            )

    else:

        elements.append(
            Paragraph("No missing skills.", styles["BodyText"])
        )

    elements.append(Spacer(1, 0.2 * inch))

    # Resume Strengths
    elements.append(
        Paragraph("<b>Resume Strengths</b>", styles["Heading2"])
    )

    if strengths:

        for item in strengths:

            elements.append(
                Paragraph(f"• {item}", styles["BodyText"])
            )

    else:

        elements.append(
            Paragraph("No strengths available.", styles["BodyText"])
        )

    elements.append(Spacer(1, 0.2 * inch))

    # Areas for Improvement
    elements.append(
        Paragraph("<b>Areas for Improvement</b>", styles["Heading2"])
    )

    if improvements:

        for item in improvements:

            elements.append(
                Paragraph(f"• {item}", styles["BodyText"])
            )

    else:

        elements.append(
            Paragraph("No improvements available.", styles["BodyText"])
        )

    elements.append(Spacer(1, 0.2 * inch))

    # AI Suggestions
    elements.append(
        Paragraph("<b>AI Suggestions</b>", styles["Heading2"])
    )

    if suggestions:

        for item in suggestions:

            elements.append(
                Paragraph(f"• {item}", styles["BodyText"])
            )

    else:

        elements.append(
            Paragraph("No suggestions available.", styles["BodyText"])
        )

    elements.append(Spacer(1, 0.3 * inch))

    # Footer
    elements.append(

        Paragraph(
            "<font color='grey'>Generated by AI Resume Ranker</font>",
            styles["Italic"]
        )

    )

    # Build PDF
    doc.build(elements)